CHART_AVAIL = ['similarity-graph','word-frequency','word-cloud','bi-gram','tri-gram','four-gram']

USECASES = ['classification','similarity','NER']

LANGUAGE = ['english','french']

CLASSIFICATION_MODELS = ['BILSTM','BIRNN','BERT-SMALL','SVC','LGBM','XGB','GPT-SMALL']

SENETENCE_EMBEDDING = ['BERT','TFIDF','UNIVERSAL-SENTENCE-ENCODER','INFERSENT']

SIMILARITY_METRICS = ['COSINE_SIMILARITY','NMSLIB']

NER_MODELS = ['BILSTMCRF','BERTNER','BERTBILSTMCRF','TRANSFORMER']

WORD_EMDEDDING = ['TFIDF','BERT','WORD2VEC','GLOVE','PYTEXT','FASTTEXT']